### ISSUE TITLE
How lambda layer handle the downsample in LambdaResNet?

### ISSUE THREAD

**Issue by qiaoran-dawnlight** [lucidrains/lambda-networks#11]
Hi,
Thanks for your clear code, i try to implement the LambdaResNet. 
Does lambda layer replace all conv2d layer? 
If so, how does lambda layer handle the downsample in conv2d, like `stride=2`?
Or just keep the conv2d if stride =2, replace only the conv2d layers in stride =1?

**Comment by PistonY** [comment]
Paper already tell you
` We apply 3x3 average-pooling with stride 2 after the lambda layers to downsample in
place of the strided convolution. `

**Comment by qiaoran-dawnlight** [comment]
@PistonY Noted ,Thanks
