### ISSUE TITLE
Code for long-range sequence?

### ISSUE THREAD

**Issue by Jyonn** [lucidrains/lambda-networks#14]
Hi Lucidrains,
I wondered this LambdaLayer is for image-like 2-d tensor. How can I apply it for long-range sequence?

Thank you!

**Comment by lucidrains** [comment]
The closest architecture to what you want would be https://github.com/lucidrains/linear-attention-transformer

**Comment by lucidrains** [comment]
And also https://github.com/lucidrains/performer-pytorch , which is still under review as well
