### ISSUE TITLE
 What does the intra-depth specifically mean?

### ISSUE THREAD

**Issue by Brave731** [lucidrains/lambda-networks#16]
The intra-depth in the paper means very abstract. What does intra-depth specifically mean?

**Comment by Fangkang515** [comment]
确实文章写的贼抽象，，，估计是大佬吧，大佬喜欢用数学解释

**Comment by lucidrains** [comment]
@Brave731 It was never made clear by the authors, but I think it is there to expand the amount of contextual information that can be summarized, kind of multi-headed
