### ISSUE TITLE
Implementation of Lambda convolution

### ISSUE THREAD

**Issue by romulus0914** [lucidrains/lambda-networks#18]
Thanks for the great work in the implementations!

I would like to ask whether there is a difference in using 'Conv2d' as suggested in Eq. 3 in the paper and your implementation of 'Conv3d'. These two convs treat the (h x w)-dimension as a 1-d sequence and a 2-d image, respectively. I believe they are quite different in concept.

Point out if I misunderstood.

Thx a lot.

**Comment by lucidrains** [comment]
@romulus0914 i believe the paper chose a 1d sequence as a simplified example, so people could visualize it better

**Comment by lucidrains** [comment]
@romulus0914 also, anonymous author reviewed that portion of the code and gave it a green light :) fairly certain it is correct

**Comment by romulus0914** [comment]
Thanks for your reply!
