### ISSUE TITLE
Lambda for a sequence of images

### ISSUE THREAD

**Issue by AmitMY** [lucidrains/lambda-networks#3]
Thanks for the quick implementation!

I have a problem where I have a sequence of images rather than 1. (a video)
So instead of having a dimension `batch, channels, height, width`, I also have after `batch` a `length` dimension to determine sequence length.

Given a known `max_length` (for the positional embedding), in forward, should `conv4d` be used instead of `3d` to allow interaction between frames?

In the paper they do mention this could serve as a general framework for sequences of images, so I wonder if you explored that in implementation (where obviously a single image is just a case where `length=1`)

**Comment by lucidrains** [comment]
@AmitMY Sure! Exactly, just an extra dimension is needed!
