### ISSUE TITLE
Can lambda network be used on NLP tasks such as language model?

### ISSUE THREAD

**Issue by Alan-Lee123** [lucidrains/lambda-networks#4]
Can lambda network be used on NLP tasks such as language model?

**Comment by lucidrains** [comment]
Yup! https://github.com/lucidrains/linear-attention-transformer is similar conceptually

**Comment by lucidrains** [comment]
But it hasn't performed as well as full attention https://openreview.net/forum?id=qVyeW-grC2k

**Comment by lorrp1** [comment]
@lucidrains what change should be made to use it for auto-regressive tasks?
