### ISSUE TITLE
Contiguity problem: "RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input."

### ISSUE THREAD

**Issue by Whiax** [lucidrains/lambda-networks#5]
It seems that LambaLayer breaks contiguity when I try it.

```
layer(x).is_contiguous()
>> False
```

I have to use .contiguous() where I train with it, is it normal?

**Comment by lucidrains** [comment]
@Whiax hmm, i'm not entirely sure, but could you try the latest version `0.2.0` and see if it is resolved?

**Comment by lucidrains** [comment]
@Whiax possibly fixed in `0.2.1`

**Comment by Whiax** [comment]
Thanks for the modification.
Well now that it's contiguous I'm pretty sure it would work, as it was also working when I applied .contiguous() after the lambdalayer during my training.
But I'm wondering about the efficiency (memory/process) of that contiguous() function, Pytorch documentation says that it's copying the tensor.
https://pytorch.org/docs/stable/tensor_view.html
At least maybe it's possible to only call .contiguous() during the training.
I'll update when I can do more experiments and I'm also wondering if other people have had the problem when there wasn't the .contiguous() at the end

**Comment by lucidrains** [comment]
@Whiax ok, I reordered some einsums to avoid that contiguous call https://github.com/lucidrains/lambda-networks/releases/tag/0.2.2 let me know if that works for you!

**Comment by Whiax** [comment]
Ok now it's working properly without .contiguous(), thanks!
Though, I don't see much difference than with .contiguous() in training time or memory consumption so maybe it wasn't that important to change ...
Anyway, thanks for the fix!
