### ISSUE TITLE
question about hybrid lambdaResnet

### ISSUE THREAD

**Issue by CoinCheung** [lucidrains/lambda-networks#9]
Hi, 

In the paper, there is this paragraph: 
>When working with hybrid LambdaNetworks, we use a single lambda layer in c4 for LambdaResNet50,
3 lambda layers for LambdaResNet101, 6 lambda layers for LambdaResNet-152/200/270/350 and
8 lambda layers for LambdaResNet-420. 

I have several questions about constructing the hybrid lambdaResnet:
1. Do we only need to replace the 3x3conv with lambda layer in the C4 stage rather than C4 and C5(as in the ablation study)?
2. When there is more than 1 lambda layers, such as the case of LambdaResNet101, are we replacing the 3x3conv with 3 lambda layers? And in the resnet50 case, we replace the 3x3conv with 1 lambda layers ?

**Comment by lucidrains** [comment]
@CoinCheung I'm not actually too sure, that wasn't too clear in the paper

**Comment by lucidrains** [comment]
https://github.com/lucidrains/lambda-networks/issues/12#issuecomment-713356700
